### ISSUE TITLE
How to implment the sql IN operator

### ISSUE THREAD

**Issue by mohammedabualsoud** [AlexaCRM/fetchxml#1]
Can you help me how to implement the IN operator please, I don't know much about fetchxml syntax?

**Comment by georged** [comment]
@mohammedabualsoud, 
not sure how we can help. If you know SQL, you can try  [sql2fetchxml converter](http://www.sql2fetchxml.com/). Also try [XrmToolbox](http://www.xrmtoolbox.com/) to build fetchxml using UI. 
HTH
George

**Comment by mohammedabualsoud** [comment]
I have implemented that part thank you.
