### ISSUE TITLE
Could not retrieve WSDL

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/fetchxml#2]
Hello Everyone,

Please, I need a Help. From last Friday I am getting a message error as you can see below:

> **Fatal error:** 
Uncaught Exception: Could not retrieve WSDL at https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl in D:\Tools\Apache\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php:1983 
**Stack trace:** 
#0 D:\Tools\Apache\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php(242): AlexaCRM\CRMToolkit\Client->retrieveWsdl('https://disco.c...') 
#1 D:\Tools\Apache\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\SoapActions.php(129): AlexaCRM\CRMToolkit\Client->getDiscoveryDOM() 
#2 D:\Tools\Apache\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\SoapActions.php(118): AlexaCRM\CRMToolkit\SoapActions->getAllDiscoverySoapActions() 
#3 D:\Tools\Apache\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\SoapActions.php(104): AlexaCRM\CRMToolkit\SoapActions->getDiscoveryAction('Execute') 
#4 D:\Tools\Apache\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php(1211): AlexaCRM\CRMToolkit\SoapActions->getSoapAction('discovery', 'Execute') 
#5 D:\Tools\ in D:\Tools\Apache\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php **on line 1983**

Please, may someone tell me what is wrong, or what should I check to solve this issue?

![image](https://user-images.githubusercontent.com/10854571/41835300-5fd663d4-7857-11e8-8c4c-e49edcdf9ad4.png)

**Comment by wizardist** [comment]
Hi @dantedantas 

We've been gathering reports about this issue. There were no significant changes in the toolkit that could trigger such behavior. Currently, we've learnt about several incidents with crm4 (Europe).

As a temporary cure, add `'ignoreSslErrors' => true` to the Settings.

HTH

**Comment by dantedantas** [comment]
Hi Pavel,
thank you very much. It is solved for now.
Waiting for a "final solution".

Best regards,
Dante

**Comment by guillaumesozen** [comment]
Thanks. Same here... after 1 month of production without problem, this morning (I don't know why) I have the same error. ignoreSslErrors save my day. We are also on crm4 (Europe) cluster...

**Comment by georged** [comment]
It usually happens during unclear certificate rollovers. Nobody is immune. That's what the flag is for :)
