### ISSUE TITLE
Could not retrieve WSDL at https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/fetchxml#3]
Hello Everyone,

I am getting the error below:

`Could not retrieve WSDL at https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl`

`Fatal error: Uncaught TypeError: Argument 1 passed to AlexaCRM\CRMToolkit\Entity\MetadataCollection::__construct() must be an instance of AlexaCRM\CRMToolkit\Client, null given, called in C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Entity\MetadataCollection.php on line 58 and defined in C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Entity\MetadataCollection.php:70 

Stack trace: 
**#0** C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Entity\MetadataCollection.php(58): AlexaCRM\CRMToolkit\Entity\MetadataCollection->__construct(NULL, NULL) 
**#1** C:\Tools\xampp\htdocs\incidentreportDEV\odataconnector.php(37): AlexaCRM\CRMToolkit\Entity\MetadataCollection::instance(NULL) 
**#2** C:\Tools\xampp\htdocs\incidentreportDEV\CRMIncidentStat.php(16): require_once('C:\\Tools\\xampp\\...') 
**#3** C:\Tools\xampp\htdocs\incidentreportDEV\index.php(32): include('C:\\Tools\\xampp\\...') 
**#4** {main} thrown in C:\Tools\xampp\htdocs\incidentreportDEV\vendor\alexacrm\php-crm-toolkit\src\Entity\MetadataCollection.php on line 70`

I didnt changed the code from the last 8 months and this error came out 4 days ago.

![image](https://user-images.githubusercontent.com/10854571/136175856-673cfdf5-af20-4ecf-a4bf-80d3e9f2d59e.png)

Here is the code from the error:

![image](https://user-images.githubusercontent.com/10854571/136176279-fcf790ad-4a8d-4670-b8b0-425958cae18f.png)

![image](https://user-images.githubusercontent.com/10854571/136176757-8180ce86-369e-482d-8074-ebc3231abfde.png)

I had a similar issue a long time ago:
https://github.com/AlexaCRM/fetchxml/issues/2

The temporary solution was add `'ignoreSslErrors' => true` to the Settings. But it doesnt work at this time.

Please, could someone help me?

BR,
Dante

**Comment by georged** [comment]
Please update the toolkit to the latest version. Discovery service has been deprecated by Microsoft and we removed it in [this commit](https://github.com/AlexaCRM/php-crm-toolkit/commit/9bc6569954666e39e95ef79a2e9e0ae5846b9d6f)

**Comment by adnanahmed** [comment]
Yup, Latest version solved the issue for me. Thanks
